name: Create PR for new commits

on:
  push:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --base beta --head main --title "TITLE" --body "BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
