name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (for GitHub CLI)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install GitHub CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/cli/cli/trunk/script/install.sh | bash

      - name: Create Pull Request
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh pr create --base beta --head main --title "Auto PR from main to beta" --body "This PR is created automatically from the main branch to the beta branch."
