name: Auto PR from main to beta

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: beta
          base: beta
          title: 'Update beta branch with latest changes from main'
          body: |
            This PR is automatically created to merge the latest changes from the main branch into the beta branch.
            
            Please review and merge as appropriate.
          labels: |
            automated-pr
            beta-update
