name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/github-cli-archive-keyring.gpg | sudo -E apt-key add -
          sudo apt-add-repository https://cli.github.com/packages/github-cli-archive-keyring.gpg
          sudo apt update
          sudo apt install gh

      - name: Create Pull Request
        run: |
          gh pr create --title "New changes from main" --body "This pull request contains the latest changes from the main branch." --head main --base beta
