name: Create PR from main to beta

on:
  push:
    branches:
      - main

jobs:
  create-pr-to-beta:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --base beta --head main --title "Update beta branch with latest changes from main" --body "This PR includes the latest changes from the main branch."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
