name: Create Pull Request on New Commits

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: actions/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "New Commits in Main"
          body: "This pull request automatically created to merge the latest changes from main branch into the target branch."
          head: main
          target: <target_branch>  # Replace with your desired target branch
