name: Create production promotion pull request
on:
  push:
    branches:
      - main
jobs:
  create-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: beta
