name: Create Pull Request
on:
  push:
    branches:
      - main
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --base beta --head main --title "Auto PR from main to beta" --body "This PR is created automatically from the main branch to the beta branch."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
